Repository ciribob/DCS-SimpleRadioStandalone, pull requests merged in 2025-09, with the labels that each got.

#854 Refresh settings on processing client transmissions regularly.
  Common/Audio/Providers/ClientTransmissionPipelineProvider.cs
Labels: bug, accepted

#845 Added separators between connection statuses
  DCS-SR-Client/UI/ClientWindow/MainWindow.xaml
Labels: accepted

#859 Fix JF-17 showing as 'disconnected' on cold start
  Scripts/DCS-SRS/Scripts/DCS-SimpleRadioStandalone.lua
Labels: bug, accepted

#855 Extract RadioExport functions to indiviual files
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/A10A.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/A10C.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/A10C2.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/A29B.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/A4E.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/AH64.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/AJS37.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/AV8BNA.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Bf109.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/C101CC.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/C101EB.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/CH47F.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/EagleII.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F14.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F15C.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F15ESE.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F16C.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F1BE.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F1CE.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F4.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F4U.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F5E.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/F86.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/FA18C.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/FBMkVI.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/FW190.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Hawk.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Hercules.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/JF17.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/KA50.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/L39.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/LFMkIX.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/M2000C.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/MB339A.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Mi24P.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Mi8.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/MiG15.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/MiG19.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/MiG21.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/MiG29.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/OH58D.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/OH6A.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/P47.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/P51.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/PUCARA.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/SA342.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/SH60B.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/SK60.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Su25.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Su27.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/T45.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/UH1H.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/UH60L.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/VSNF104C.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/VSNF4.lua
  Scripts/DCS-SRS/Scripts/DCS-SRS-Modules/Yak52.lua
  Scripts/DCS-SRS/Scripts/DCS-SimpleRadioStandalone.lua
Labels: accepted

#862 MB339 is_mode4_working() returns a number
  Scripts/DCS-SRS/Scripts/DCS-SimpleRadioStandalone.lua
Labels: bug, accepted

#866 Automatic gain control #851
  Common/Settings/GlobalSettingsStore.cs
  DCS-SR-Client/Properties/Resources.Designer.cs
  DCS-SR-Client/Properties/Resources.resx
  DCS-SR-Client/UI/ClientWindow/ClientSettingsControl/ClientSettings.xaml
  DCS-SR-Client/UI/ClientWindow/ClientSettingsControl/ClientSettingsViewModel.cs
Labels: Feature Request, accepted

#867 Settings versioning
  Common/Settings/GlobalSettingsStore.cs
Labels: Feature Request, accepted

#879 AH64D: Allow IDENT in EMERG
  Scripts/DCS-SRS/Scripts/DCS-SimpleRadioStandalone.lua
Labels: bug, accepted

#893 Compressor sidechain
  Common/Audio/Dsp/EnvelopeDetector.cs
  Common/Audio/Dsp/SidechainCompressor.cs
  Common/Audio/Models/RadioModel.cs
  Common/Audio/Providers/SidechainCompressorProvider.cs
  DCS-SR-Client/RadioModels/HOWTO.md
Labels: accepted

#858 Replace voice fx on/off with wet/dry slider
  Common/Audio/Providers/ClientEffectsPipeline.cs
  Common/Audio/Providers/ClientTransmissionPipelineProvider.cs
  Common/Settings/ProfileSettingsStore.cs
  DCS-SR-Client/Properties/Resources.Designer.cs
  DCS-SR-Client/Properties/Resources.resx
  DCS-SR-Client/UI/ClientWindow/ClientSettingsControl/ClientSettings.xaml
  DCS-SR-Client/UI/ClientWindow/ClientSettingsControl/ClientSettingsViewModel.cs
Labels: Feature Request, accepted

#894 Improve saturation
  Common/Audio/Providers/SaturationProvider.cs
Labels: accepted

#895 Update radio profiles with sidechain compressor
  DCS-SR-Client/RadioModels/WW2_WIP/arc5.json
  DCS-SR-Client/RadioModels/WW2_WIP/fug16zy.json
  DCS-SR-Client/RadioModels/WW2_WIP/r1155.json
  DCS-SR-Client/RadioModels/WW2_WIP/scr522a.json
  DCS-SR-Client/RadioModels/WW2_WIP/t1154.json
  DCS-SR-Client/RadioModels/arc131.json
  DCS-SR-Client/RadioModels/arc134.json
  DCS-SR-Client/RadioModels/arc164.json
  DCS-SR-Client/RadioModels/arc186.json
  DCS-SR-Client/RadioModels/arc201d.json
  DCS-SR-Client/RadioModels/arc210.json
  DCS-SR-Client/RadioModels/arc220.json
  DCS-SR-Client/RadioModels/arc222.json
  DCS-SR-Client/RadioModels/arc27.json
  DCS-SR-Client/RadioModels/arc51.json
  DCS-SR-Client/RadioModels/baklan5.json
  DCS-SR-Client/RadioModels/intercom.json
  DCS-SR-Client/RadioModels/jadro1a.json
  DCS-SR-Client/RadioModels/link16.json
  DCS-SR-Client/RadioModels/r800.json
  DCS-SR-Client/RadioModels/r828.json
  DCS-SR-Client/RadioModels/r832m.json
  DCS-SR-Client/RadioModels/r852.json
  DCS-SR-Client/RadioModels/r862.json
  DCS-SR-Client/RadioModels/r863.json
  DCS-SR-Client/RadioModels/r864.json
  DCS-SR-Client/RadioModels/rsi6k.json
Labels: accepted

#902 Ensure sidechain has an actual copy of the signal.
  Common/Audio/Models/RadioModel.cs
  Common/Audio/Providers/NoopSampleProvider.cs
  Common/Audio/Providers/SidechainCompressorProvider.cs
Labels: bug, accepted
